### ISSUE TITLE
Use CDN for JS/CSS libraries

### ISSUE THREAD

**Issue by Fcmam5** [open-minds/open-minds.github.io#10]
Why you're keeping JS & CSS libraries in this rpeo? Why not just using CDN?

I got some CSS URLs for you with [integrity and crossorigin attributes](https://stackoverflow.com/questions/32039568/what-are-the-integrity-and-crossorigin-attributes) for you :smile: :

Font awesome:
`<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">`

Bootstrap
`<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">`

Animate CSS
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css" integrity="sha256-PHcOkPmOshsMBC+vtJdVr5Mwb7r0LkSVJPlPrp/IMpU=" crossorigin="anonymous" />`

Ionic icons V2.0
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.0/css/ionicons.min.css" integrity="sha256-3iu9jgsy9TpTwXKb7bNQzqWekRX7pPK+2OLj3R922fo=" crossorigin="anonymous" />`

Owl carousel
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" integrity="sha256-UhQQ4fxEeABh4JrcmAJ1+16id/1dnlOEVCFOxDef9Lw=" crossorigin="anonymous" />`

Lightbox
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.1/css/lightbox.min.css" integrity="sha256-tBxlolRHP9uMsEFKVk+hk//ekOlXOixLKvye5W2WR5c=" crossorigin="anonymous" />`

And, please also update JS Urls

Example Jquery:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>`

How to get this script tag?
Go to: https://cdnjs.com/libraries/jquery/

Then:
![Screenshot from 2020-01-01 02-48-50](https://user-images.githubusercontent.com/9090674/71637351-50e67b80-2c41-11ea-97fe-a57bab83eda9.png)

---

After replacing the local `/lib` resources, I believe that we will be good to remove the lib folder so we can have a lighter repository :)

Also, please don't forget #8

**Comment by oussamabouchikhi** [comment]
Working on it

**Comment by Fcmam5** [comment]
Thank you! Good luck
